/* tslint:disable */
/* eslint-disable */
/**
 * MH rehabilitation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MedList,
    MedListFromJSON,
    MedListToJSON,
} from '../models';

export interface ListPharmacologicalRequest {
    medId?: string;
    time?: string;
    page?: number;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * List of medicaments
     */
    async listPharmacologicalRaw(requestParameters: ListPharmacologicalRequest): Promise<runtime.ApiResponse<Array<MedList>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.medId !== undefined) {
            queryParameters['medId'] = requestParameters.medId;
        }

        if (requestParameters.time !== undefined) {
            queryParameters['time'] = requestParameters.time;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rehabilitation/pharmacological`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MedListFromJSON));
    }

    /**
     * List of medicaments
     */
    async listPharmacological(requestParameters: ListPharmacologicalRequest): Promise<Array<MedList>> {
        const response = await this.listPharmacologicalRaw(requestParameters);
        return await response.value();
    }

}
