/* tslint:disable */
/* eslint-disable */
/**
 * MH rehabilitation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedList
 */
export interface MedList {
    /**
     * 
     * @type {string}
     * @memberof MedList
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MedList
     */
    medId?: string;
    /**
     * 
     * @type {string}
     * @memberof MedList
     */
    medType?: string;
    /**
     * 
     * @type {string}
     * @memberof MedList
     */
    time?: string;
    /**
     * taken | not taken
     * @type {string}
     * @memberof MedList
     */
    status?: string;
}

export function MedListFromJSON(json: any): MedList {
    return MedListFromJSONTyped(json, false);
}

export function MedListFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'medId': !exists(json, 'medId') ? undefined : json['medId'],
        'medType': !exists(json, 'medType') ? undefined : json['medType'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function MedListToJSON(value?: MedList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'medId': value.medId,
        'medType': value.medType,
        'time': value.time,
        'status': value.status,
    };
}


